openapi: 3.0.3
info:
  title: API de Química
  description: API para generar permutaciones de moléculas y obtener imágenes basadas en SMILES.
  version: 1.0.0

tags:
  - name: Permutations
    description: Operaciones para generar permutaciones de moléculas
  - name: Images
    description: Operaciones para obtener imágenes de moléculas
  - name: Version
    description: Operaciones para obtener la versión de la API

paths:
  /generatePermutations:
    post:
      summary: Generar permutaciones de moléculas
      description: Genera todas las permutaciones posibles de una molécula principal con una lista de sustituyentes.
      tags:
        - Permutations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mainMolecule:
                  $ref: "#/components/schemas/Molecule"
                substitutes:
                  type: array
                  items:
                    $ref: "#/components/schemas/Molecule"
      responses:
        '200':
          description: Lista de moléculas generada exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneratedMolecule"
        '400':
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /getImage/{smile}:
    get:
      summary: Obtener imagen de una molécula en formato SMILES
      description: Retorna la imagen de una molécula basada en un SMILES proporcionado.
      tags:
        - Images
      parameters:
        - name: smile
          in: path
          required: true
          schema:
            type: string
          description: SMILES que describe la molécula de la cual se desea obtener la imagen.
      responses:
        '200':
          description: Imagen de la molécula en formato JPEG.
          content:
            'image/jpeg':
              schema:
                type: string
                format: binary
        '404':
          description: No se pudo generar la imagen correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /getImageWithSubstitute/{smile}:
    post:
      summary: Obtener imagen de una molécula con su sustituyente en formato SMILES
      description: Retorna la imagen de una molécula y su sustituyente basados en un SMILES proporcionado.
      tags:
        - Images
      parameters:
        - name: smile
          in: path
          required: true
          schema:
            type: string
          description: SMILES que describe la molécula principal de la cual se desea obtener la imagen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mainMolecule:
                  $ref: "#/components/schemas/Molecule"
                substitute:
                  $ref: "#/components/schemas/Molecule"
      responses:
        '200':
          description: Imagen de la molécula y su sustituyente en formato JPEG.
          content:
            'image/jpeg':
              schema:
                type: string
                format: binary
        '404':
          description: No se encontró la imagen para el SMILES especificado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /getImageWithSubstitute:
    post:
      summary: Obtener imagen de una molécula con su sustituyente
      description: Retorna la imagen de una molécula y su sustituyente.
      tags:
        - Images
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mainMolecule:
                  $ref: "#/components/schemas/Molecule"
                substitute:
                  $ref: "#/components/schemas/Molecule"
      responses:
        '200':
          description: Imagen de la molécula y su sustituyente en formato JPEG.
          content:
            'image/jpeg':
              schema:
                type: string
                format: binary
        '400':
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /version:
    get:
      summary: Obtener la versión de la API
      description: Retorna la versión actual de la API de química.
      tags:
        - Version
      responses:
        '200':
          description: Versión de la API.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "1.0.0"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

components:
  schemas:
    Molecule:
      type: object
      properties:
        smile:
          type: string
          description: SMILES de la molécula.
        nombre:
          type: string
          description: Nombre de la molécula.
        atomosSeleccionados:
          type: array
          items:
            type: integer
          description: Lista de átomos seleccionados.
        tieneHidrogenosImplicitos:
          type: boolean
          description: Indica si la molécula tiene hidrógenos implícitos.

    GeneratedMolecule:
      type: object
      properties:
        id:
          type: integer
          description: Identificador único de la molécula generada.
        nombreMolecula:
          type: string
          description: Nombre de la molécula generada.
        moleculaPrincipal:
          $ref: "#/components/schemas/Molecule"
          description: Detalles de la molécula principal.
        sustituyente:
          $ref: "#/components/schemas/Molecule"
          description: Detalles del sustituyente aplicado.
        posicionMoleculaPrincipal:
          type: integer
          description: Posición de la molécula principal.
        posicionMoleculaSustituyente:
          type: integer
          description: Posición del sustituyente en la molécula generada.

    ErrorObject:
      type: object
      properties:
        descripcion:
          type: string
          description: Descripción del error.
        codigo:
          type: integer
          description: Código numérico del error http.
        detalles:
          type: string
          description: Detalles adicionales sobre el error.
