name: Generar código

on:
    workflow_dispatch:
    push:

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Checkout api client
        uses: actions/checkout@v4
        with:
          repository: chem-gl/smile-it-front-api
          path: api-clien
          ssh-key: ${{ secrets.API_CLIENT_REPO_KEY }}
          persist-credentials: true

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Verificar existencia de pnpm-lock.yaml
        run: |
          if [ ! -f "api-client/pnpm-lock.yaml" ]; then
            echo "El archivo pnpm-lock.yaml no existe. Ejecutando pnpm install..."
            pnpm install
          else
            echo "El archivo pnpm-lock.yaml ya existe. No se ejecutará pnpm install."
          fi
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm
         

      # Se necesita Java para poder ejecutar OpenAPI Generator
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          java-package: jre

      - name: Eliminar versión anterior del código autogenerado
        run: xargs rm < .openapi-generator/FILES || rm -rf .openapi-generator || true #true para que no falle si no existe
        working-directory: api-client

      - name: Copiar especificación de OpenAPI
        run: cp uam-registro-aspirantes.yaml api-client/api-docs.yaml

      - name: Generar código
        run: pnpx @openapitools/openapi-generator-cli@2.7.0 generate --generator-key api-client
        working-directory: api-client

      - name: Eliminar especificación de OpenAPI
        run: rm api-docs.yaml
        working-directory: api-client

      - name: Instalar dependencias faltantes
        run: pnpm i -D tslib@2.6.2
        working-directory: api-client

      - name: Commit cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualizar código autogenerado a la versión ${{ needs.check-version-change.outputs.new-version }}"
        working-directory: api-client

      - name: Push cambios
        run: git push
        working-directory: api-client
